name: ClassicEdit
main: pl.cba.knest.ClassicEdit.ClassicEdit
version: 0.9
description: 
             ClassicEdit adds Minecraft-classic commands based on McLawl engine.
commands:
  cuboid:
    description: Creates a cuboid.
    usage: /cuboid <block>
    aliases: [cube, z]
  maze:
    description: Creates a maze.
    usage: /maze <block>
  pause:
    description: Pauses cuboids.
    aliases: [p]
  spheroid:
    description: Creates a spheroid.
    usage: /spheroid <block>
    aliases: [ellipsoid, e]
  persp:
    description: Creates a perspective creation.
    usage: /perspective <block>
    aliases: [perspective]
  line:
    description: Creates line.
    usage: /line <block>
    aliases: [li]
  gun:
    description: Activates gun.
    usage: /gun <block>
  paste:
    description: Pastes a paste.
    usage: /paste
    aliases: [/v]
  load:
    description: Loads a schematic from /ClassicEdit/
    usage: /load <file>
  block:
    description: Sets the filling.
    aliases: [b]